//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp1.Properties.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт может занять некоторое время, пожалуйста подождите....
        /// </summary>
        public static string AwaitExport {
            get {
                return ResourceManager.GetString("AwaitExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт может занять некоторое время, пожалуйста подождите....
        /// </summary>
        public static string AwaitImport {
            get {
                return ResourceManager.GetString("AwaitImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор даты.
        /// </summary>
        public static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали файл.
        /// </summary>
        public static string ChooseFileEx {
            get {
                return ResourceManager.GetString("ChooseFileEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string CityWord {
            get {
                return ResourceManager.GetString("CityWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение к БД завершено успешно.
        /// </summary>
        public static string ConnectionToDbSuccesfull {
            get {
                return ResourceManager.GetString("ConnectionToDbSuccesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        public static string CountryWord {
            get {
                return ResourceManager.GetString("CountryWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Созданную выборку можно увидеть в созданном файле: &quot;{0}&quot; либо на страницах просмотра.
        /// </summary>
        public static string CreatedSelectionView {
            get {
                return ResourceManager.GetString("CreatedSelectionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные загружены в базу даных и готовы к экспорту.
        /// </summary>
        public static string DataImported {
            get {
                return ResourceManager.GetString("DataImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные подгружаются....
        /// </summary>
        public static string DataIsLoading {
            get {
                return ResourceManager.GetString("DataIsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string DateWord {
            get {
                return ResourceManager.GetString("DateWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите данные для выборки, а затем нажмите кнопку экспорта.
        /// </summary>
        public static string DefaultExportTextBoxMessage {
            get {
                return ResourceManager.GetString("DefaultExportTextBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите, пожалуйста, файл для импорта.
        /// </summary>
        public static string DefaultImportTextBoxMessage {
            get {
                return ResourceManager.GetString("DefaultImportTextBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввод.
        /// </summary>
        public static string EnterButton {
            get {
                return ResourceManager.GetString("EnterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите релевантную строку подключения к БД:.
        /// </summary>
        public static string EnterConnectionString {
            get {
                return ResourceManager.GetString("EnterConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите данные для выборки для экспорта:.
        /// </summary>
        public static string EnterDataForSelection {
            get {
                return ResourceManager.GetString("EnterDataForSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В Excel файле нет доступной страницы или он пуст.
        /// </summary>
        public static string ExExcelFileIsEmpty {
            get {
                return ResourceManager.GetString("ExExcelFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка открытия файла.
        /// </summary>
        public static string ExFileOpening {
            get {
                return ResourceManager.GetString("ExFileOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка сохранения файла.
        /// </summary>
        public static string ExFileSaving {
            get {
                return ResourceManager.GetString("ExFileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможен только буквенный ввод!.
        /// </summary>
        public static string ExLetterInput {
            get {
                return ResourceManager.GetString("ExLetterInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт.
        /// </summary>
        public static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не валидатная строка подключения к БД.
        /// </summary>
        public static string ExWrongConnectionString {
            get {
                return ResourceManager.GetString("ExWrongConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат файла.
        /// </summary>
        public static string ExWrongFileFormat {
            get {
                return ResourceManager.GetString("ExWrongFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл {0} был успешно создан.
        /// </summary>
        public static string FileCreatedSuccesfully {
            get {
                return ResourceManager.GetString("FileCreatedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstNameWord {
            get {
                return ResourceManager.GetString("FirstNameWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение установлено.
        /// </summary>
        public static string HeaderConnectionEstablished {
            get {
                return ResourceManager.GetString("HeaderConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при подключении к БД.
        /// </summary>
        public static string HeaderConnectionEx {
            get {
                return ResourceManager.GetString("HeaderConnectionEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт завершён!.
        /// </summary>
        public static string HeaderExportCompleted {
            get {
                return ResourceManager.GetString("HeaderExportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при создании файла.
        /// </summary>
        public static string HeaderExportEx {
            get {
                return ResourceManager.GetString("HeaderExportEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт завершен!.
        /// </summary>
        public static string HeaderImportCompleted {
            get {
                return ResourceManager.GetString("HeaderImportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при импорте.
        /// </summary>
        public static string HeaderImportEx {
            get {
                return ResourceManager.GetString("HeaderImportEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный ввод.
        /// </summary>
        public static string HeaderInvalidImput {
            get {
                return ResourceManager.GetString("HeaderInvalidImput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при переходе на страницу.
        /// </summary>
        public static string HeaderOpenPageEx {
            get {
                return ResourceManager.GetString("HeaderOpenPageEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попробуйте снова.
        /// </summary>
        public static string HeaderTryAgain {
            get {
                return ResourceManager.GetString("HeaderTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла непредвиденная ошибка.
        /// </summary>
        public static string HeaderUnexpectedEx {
            get {
                return ResourceManager.GetString("HeaderUnexpectedEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При создании выборки произошла непредвиденная ошибка.
        /// </summary>
        public static string HeaderUnexpectedSelectionEx {
            get {
                return ResourceManager.GetString("HeaderUnexpectedSelectionEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подождите!.
        /// </summary>
        public static string HeaderWaitPlease {
            get {
                return ResourceManager.GetString("HeaderWaitPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при открытии файла.
        /// </summary>
        public static string HeadetOpenFileEx {
            get {
                return ResourceManager.GetString("HeadetOpenFileEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт.
        /// </summary>
        public static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastNameWord {
            get {
                return ResourceManager.GetString("LastNameWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Особые текстовые файлы (*.csv) | *.csv.
        /// </summary>
        public static string OpenCsvFileExtensionFilter {
            get {
                return ResourceManager.GetString("OpenCsvFileExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel документ|*.xlsx|Xml документ|*.xml.
        /// </summary>
        public static string OpenExcelXmlFileExtensionFilter {
            get {
                return ResourceManager.GetString("OpenExcelXmlFileExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string OpenFileButton {
            get {
                return ResourceManager.GetString("OpenFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убедитесь что:
        ///1) файл не открыт в другом приложении
        ///2) это один из созданных вами файлов
        ///3) файл не повреждён.
        /// </summary>
        public static string OpenFileForViewEx {
            get {
                return ResourceManager.GetString("OpenFileForViewEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string PatronymicWord {
            get {
                return ResourceManager.GetString("PatronymicWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel документ|*.xlsx|Xml документ|*.xml.
        /// </summary>
        public static string SaveFileExtensionFilter {
            get {
                return ResourceManager.GetString("SaveFileExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string UsersWord {
            get {
                return ResourceManager.GetString("UsersWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string UserWord {
            get {
                return ResourceManager.GetString("UserWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр
        ///файла.
        /// </summary>
        public static string ViewFileButton {
            get {
                return ResourceManager.GetString("ViewFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр
        ///выборки.
        /// </summary>
        public static string ViewSelectionButton {
            get {
                return ResourceManager.GetString("ViewSelectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лист1.
        /// </summary>
        public static string WorksheetWord {
            get {
                return ResourceManager.GetString("WorksheetWord", resourceCulture);
            }
        }
    }
}
